### ISSUE TITLE
Open Recreation Data

### ISSUE THREAD

**Issue by RapsIn4** [uWaterloo/OpenData#137]
Can we get an API for the open recreation schedule? The school's website is awful.

**Comment by RuijieZ** [comment]
Any update on this?

**Comment by nathanv** [comment]
Hello @RuijieZ thanks for your inquiry. First of all, thank you for participating here.
We are working together with the Student Portal team and Athletics to get access to the data especially since it is a highly requested feature in Portal. We still cannot give you an exact time when we will get access but you can be sure we will let you know when we do.
