### ISSUE TITLE
Endpoint for dates where classes are not held

### ISSUE THREAD

**Issue by zachomedia** [uWaterloo/OpenData#158]
Hello OpenData,

A handy endpoint (especially for people making calendar apps (ex. Portal)) could benefit from an endpoint which indicated which days classes are not held (when they normal are—like Reading Week).

This information is related to holidays, and a couple of ideas could work for implementing this (I'll leave it to the experts):
1. Modify the holidays endpoint to include all days where classes are not held and add an extra field indicating if it is a holiday or not (this is probably preferred)
2. Add a new endpoint with days where classes are not held (probably least preferred because you'd have to mix information from two sources or have duplicate information)

This is an extension on the request for start/end dates of terms (#139).

**Comment by KartikTalwar** [comment]
Hey @zachomedia are there/can you think cases other than exam time (days after last day of classes) and reading week where there are no classes? I believe that the important dates endpoint is still under development (about to be released soon) and it'll indicate the start and end dates for a term but the technicality for the first suggestion solution is that a holiday implies day off for students and staff whereas reading week and exam time are only applicable to students.

cc @nathanv

**Comment by zachomedia** [comment]
Hey @KartikTalwar,

There are a couple of cases that I think more detailed schedule information could be useful:

1. No Classes (ex. holidays, reading week, etc.)
2. Modified schedule days (ex: On Monday, April 6 we will be following Friday schedule to makeup for the lost Friday on Good Friday ([Important Dates](https://uwaterloo.ca/quest/undergraduate-students/important-dates/important-dates-2014-2015)))

Right now there is no way to get this information from OpenData (except for University Holidays). I don't know what the Important Dates response will return, but a need for structured schedule information is needed.

For example, something like this would be very useful:
```json
[{
   "date":"2015-02-20",
   "classes_held":false,
},
{
   "date":"2015-04-06",
   "classes_held":true,
   "schedule":"F"
}]
```

I forgot when I first submitted this about modified schedule days, so my first implementation idea probably won't work anymore.

**Comment by nathanv** [comment]
@zachomedia @KartikTalwar 
I'm going to chime in here. I'm about to embark on a project in an upcoming sprint in which I will build a Drupal form system that will be directly controllable by the same person that updates the current unstructured drupal page seen [here](https://uwaterloo.ca/quest/undergraduate-students/important-dates/important-dates-2015-2016). This system will spit out JSON which we will then Proxy through the Open Data api.

We do have an alpha Important Dates API but we won't be releasing it to the public because it's not being updated by the information stewards. The new interface will be.

I really like Zachary's idea of appending "classes_held":  true or classes_held" : false so I'll be sure to implement that.

That being said, in the situation where we have to record unscheduled days off (snow days, etc), we will have to implement a specific tool for that. The steward for that sort of data are the folks that implement the home page. It will make sense to create a content type where folks can add a School Closed piece of content and then we serve it up via Open Data.

**Comment by nathanv** [comment]
I still haven't addressed @zachomedia [comment ](https://github.com/uWaterloo/OpenData/issues/158#issuecomment-75314300): 

> Modified schedule days (ex: On Monday, April 6 we will be following Friday schedule to makeup for the lost Friday on Good Friday
 
For this method, we can append the property ```"rescheduled":true``` or ```"rescheduled":false``` along with 

```JSON
"rescheduled_times": {
         "start":"2014-11-24T00:00:00-05:00",
         "end":"2014-11-24T00:00:00-05:00"
      }
```

If there is a date that does not get rescheduled, we will set ```"rescheduled_times":null```

**Comment by james05** [comment]
Hey Nathan,

Any update on if an important dates endpoint is going to be published soon?
