### ISSUE TITLE
Minor - missing wcms news entry in feed

### ISSUE THREAD

**Issue by JoeRadman** [uWaterloo/OpenData#186]
Hi,

I'm looking at this:
https://uwaterloo.ca/campus-wellness/news

There's a news entry on May 19 that is not in the API feed. It's in the XML rss feed.
https://api.uwaterloo.ca/v2/news/campus-wellness.json?key=

Thanks guys

Joe

**Comment by zachomedia** [comment]
Thanks @JoeRadman. I've forced a manual update of the data in Open Data and the news entry for May 19th is there now.

I'll have to investigate what's up with the pings, since this isn't the first time data has been missing. I'm currently running an update across all sites in case others are missing entries as well.

**Comment by JoeRadman** [comment]
Thanks Zac



Joe Radman
University of Waterloo
