### ISSUE TITLE
Outdated course data for terms endpoints

### ISSUE THREAD

**Issue by jjstockton** [uWaterloo/OpenData#189]
The API returns outdated course data for all `/terms` endpoints. For example, https://api.uwaterloo.ca/v2/terms/1179/courses.json shows
```
{
   {
      "subject":"ECE",
      "catalog_number":"105",
      "units":0.5,
      "title":"Physics of Electrical Engineering 1"
   }
}
```
even though ECE 105 was renamed [Classical Mechanics](http://www.ucalendar.uwaterloo.ca/1718/COURSE/course-ECE.html#ECE105) as of Fall 2017.

**Comment by sbobkin** [comment]
Hi, 

Thank you for reporting this issue. We're aware of this issue in the term, course, and scheduling data feeds. The open data project has transitioned to a different team and we plan to roll out these data sets with additional feature and fixes. However this will be on a new platform and we'll communicate the time lines for that in the near future. 

As it stands for the current iteration this issue is fairly fundamental and comes from how the term data is treated at the core data model level. As such we will not be fixing it in the current API version.
