### ISSUE TITLE
Data Request - Required courses per major/minor

### ISSUE THREAD

**Issue by MrMiaoMiao** [uWaterloo/OpenData#192]
I was wondering if it would be possible to get a list of majors/minors/joint programs and their required courses. I am working on a degree tracking widget for UW Portal.

**Comment by sbobkin** [comment]
Hi, 

Thanks for the request. I think we could look at the programs listing as a data endpoint. I don't believe there exists a data set that describes the required courses and requirements for these programs. It's documented in writing in the academic calendars, but doesn't exist as data. 

I'll take note of this request because it's something we've heard before, and at least the listing we will be addressing in the next version of the Open Data API (see the home page comment about the current state). The required courses data is as of right now a very far future possibility.
