### ISSUE TITLE
Are v2 course schedules still reliable?

### ISSUE THREAD

**Issue by wtyanan** [uWaterloo/OpenData#204]
Since course schedules (i.e. available spots, sections, and instructor etc.) information are not yet available in v3, can I use v2 for now?

**Comment by sbobkin** [comment]
Yes, v2 is as accurate as it was before and continues to update. There are known issues in the data around courses across terms, and requirements, but should be minimal in practical use. 

There was recently a bug because of term codes being hard coded in the system, and there may be other issues. Schedules in v3 is a priority, but we're working through background changes & blockers.
