### ISSUE TITLE
Display course instructor and location info for Watiam authenticated users

### ISSUE THREAD

**Issue by yxyyeah** [uWaterloo/OpenData#226]
It would be helpful if UWaterloo student and staff can still access the course instructor and location info, if they pass along their Watiam credentials.

**Comment by sbobkin** [comment]
Hi @yxyyeah 

At this time we cannot publish that information again. Even if we put it behind authentication, the Open Data API is no longer the correct place for this data. 

The intent and spirit of the open data initiative is to make data available that we do not have to protect, and brings value from being used. Since the personal details and location information no longer satisfy one of those criteria the open data API is not the right place for it. 

I understand the removal was on a very short time frame, but we're restricted by the guidance we receive from the data stewards and the university administration. 

If you think you have a project that requires this data you can submit a request via this Registrar Office form https://uwaterloo.ca/registrar-resources/form/webform-105
