### ISSUE TITLE
Request: Telephone White Pages Data

### ISSUE THREAD

**Issue by axyjo** [uWaterloo/OpenData#56]
Serve up data from [here](http://www.ist.uwaterloo.ca/phone/pers_dir.html) through the API. Let me know if you want me to write a scraper for this, although it seems that IST has control over that resource, so they should be able to send the raw file or something that's used to generate that page.

**Comment by axyjo** [comment]
@KartikTalwar, @gdmalet Any updates?  It's been nearly two years since I opened the ticket.

**Comment by nathanv** [comment]
It's in an upcoming sprint.                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Akshay JoshiSent: Friday, February 20, 2015 20:16To: uWaterloo/OpenDataReply To: uWaterloo/OpenDataSubject: Re: [OpenData] Request: Telephone White Pages Data (#56)@KartikTalwar, @gdmalet Any updates?  It's been nearly two years since I opened the ticket.

—Reply to this email directly or view it on GitHub.

**Comment by axyjo** [comment]
Any way for me to help out?

**Comment by nathanv** [comment]
Maybe yes! I will consult with the team next week. Perhaps we can accelerate timelines if you get involved. There has been firm talk to modernise the app internally but the web group has committed to first feeding Open Data before we build something. We’ve determined that we need to do a bunch of ldap queries to filter the data  from the super set. The main thing is we want to enable developers to replicate the find as you type functionality one long web page affords. Things that would help:If you play around with LDAP (login to the vpn first) and then figure out what search filters we need. @gdmalet might also chime in here. LDAP info: https://uwaterloo.ca/information-systems-technology/services/email/mailservices/set-up Most importantly: if you spec out the endpoints / response you want to see, that will help inform our final design.                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Akshay JoshiSent: Friday, February 20, 2015 20:21To: uWaterloo/OpenDataReply To: uWaterloo/OpenDataCc: Nathan VexlerSubject: Re: [OpenData] Request: Telephone White Pages Data (#56)Any way for me to help out?

—Reply to this email directly or view it on GitHub.

**Comment by axyjo** [comment]
Based on initial probing, it seems like staff have the 'departmentNumber' field populated, but students don't.
